CREATE TABLE "BPEL_PROCESS"
(
"ID" NUMBER NOT NULL,
"NAME" VARCHAR2 (30) NOT NULL
)
;
CREATE TABLE "BPEL_USR_PROC"
(
"ID" NUMBER NOT NULL,
"USR_ID" NUMBER,
"PROC_ID" NUMBER
)
;
CREATE TABLE "BPEL_REVISION"
(
"ID" NUMBER NOT NULL,
"REVISION" VARCHAR2 (5) NOT NULL
)
;
CREATE TABLE "BPEL_PROC_REV"
(
"ID" NUMBER NOT NULL,
"PROC_ID" NUMBER NOT NULL,
"REV_ID" NUMBER NOT NULL
)
;
CREATE TABLE "BPEL_ACTIVITY"
(
"ID" NUMBER NOT NULL,
"NAME" VARCHAR2 (11) NOT NULL,
"PROC_ID" NUMBER NOT NULL
)
;
CREATE TABLE "BPEL_USER"
(
"ID" NUMBER NOT NULL,
"USERNAME" VARCHAR2 (20) NOT NULL,
"CREDENTIAL" VARCHAR2 (30) NOT NULL,
"IPHOST" VARCHAR2 (10),
"IS_ADMIN" NUMBER DEFAULT 0 NOT NULL
)
;
ALTER TABLE "BPEL_PROCESS"
ADD CONSTRAINT "BPEL_PROCESSES_PK1" PRIMARY KEY
(
"ID"
)
 ENABLE
;
ALTER TABLE "BPEL_USR_PROC"
ADD CONSTRAINT "BPEL_USR_PROC_PK1" PRIMARY KEY
(
"ID"
)
 ENABLE
;
ALTER TABLE "BPEL_USR_PROC"
ADD CONSTRAINT "BPEL_USR_PROC_UK" UNIQUE
(
"USR_ID",
"PROC_ID"
)
 ENABLE
;
ALTER TABLE "BPEL_REVISION"
ADD CONSTRAINT "REV_PK1" PRIMARY KEY
(
"ID"
)
 ENABLE
;
ALTER TABLE "BPEL_PROC_REV"
ADD CONSTRAINT "BPEL_PROC_REV_PK1" PRIMARY KEY
(
"ID"
)
 ENABLE
;
ALTER TABLE "BPEL_ACTIVITY"
ADD CONSTRAINT "BPEL_ACTIVITY_PK1" PRIMARY KEY
(
"ID"
)
 ENABLE
;
ALTER TABLE "BPEL_USER"
ADD CONSTRAINT "TABLE1_PK1" PRIMARY KEY
(
"ID"
)
 ENABLE
;
ALTER TABLE "BPEL_USER"
ADD CONSTRAINT "BPEL_USERS_UK_USERNAME" UNIQUE
(
"USERNAME"
)
 ENABLE
;
COMMENT ON COLUMN "BPEL_USR_PROC".ID IS 'pk column'
;
COMMENT ON COLUMN "BPEL_USR_PROC".USR_ID IS 'id coming from BPEL_USER'
;
COMMENT ON COLUMN "BPEL_USR_PROC".PROC_ID IS 'id coming from BPEL_PROCESS'
;
COMMENT ON COLUMN "BPEL_ACTIVITY".ID IS 'pk'
;
COMMENT ON COLUMN "BPEL_ACTIVITY".NAME IS 'name of the activity'
;
COMMENT ON COLUMN "BPEL_ACTIVITY".PROC_ID IS 'id of the process the activity belongs to'
;
COMMENT ON COLUMN "BPEL_USER".ID IS 'User PK'
;
COMMENT ON COLUMN "BPEL_USER".USERNAME IS 'the unique name of the user'
;
COMMENT ON COLUMN "BPEL_USER".IPHOST IS 'The IP address of the user if known'
;
COMMENT ON COLUMN "BPEL_USER".IS_ADMIN IS '0 for no, 1 for yes'
;
COMMENT ON TABLE "BPEL_USR_PROC" IS 'Intersection table for BPEL_USER and BPEL_PROCESS '
;
COMMENT ON TABLE "BPEL_ACTIVITY" IS 'table that stores acivities'
;
ALTER TABLE "BPEL_USR_PROC"
ADD CONSTRAINT "BPEL_USR_PROC_USER_FK" FOREIGN KEY
(
"USR_ID"
)
REFERENCES "BPEL_USER"
(
"ID"
) ENABLE
;
ALTER TABLE "BPEL_USR_PROC"
ADD CONSTRAINT "BPEL_USR_PROC_PROCESS_FK" FOREIGN KEY
(
"PROC_ID"
)
REFERENCES "BPEL_PROCESS"
(
"ID"
) ENABLE
;
ALTER TABLE "BPEL_PROC_REV"
ADD CONSTRAINT "BPEL_PROC_REV_FK" FOREIGN KEY
(
"PROC_ID"
)
REFERENCES "BPEL_PROCESS"
(
"ID"
) ENABLE
;
ALTER TABLE "BPEL_PROC_REV"
ADD CONSTRAINT "BPEL_PROC_REV_FK1" FOREIGN KEY
(
"REV_ID"
)
REFERENCES "BPEL_REVISION"
(
"ID"
) ENABLE
;
ALTER TABLE "BPEL_ACTIVITY"
ADD CONSTRAINT "BPEL_ACTIVITY_FK" FOREIGN KEY
(
"PROC_ID"
)
REFERENCES "BPEL_PROCESS"
(
"ID"
) ENABLE
;
