/**
 *
 * $Header: upgrade_10131_10133_oracle.sql 16-may-2007.12:59:27 mchinnan Exp $
 *
 * upgrade_10131_10133_oracle.sql
 *
 * Copyright (c) 2006, 2007, Oracle. All rights reserved.  
 *
 *    NAME
 *      upgrade_10131_10133_oracle.sql
 *
 *    DESCRIPTION
 *      Upgrade script for 10.1.3.1 to 10.1.3.3 schema
 *
 *    NOTES
 *    bug 5995309: added an index to cube_instance table for bpel console
 *    bug 5672391: Change to admin_list_cx
 *    bug 5633507: new table wi_fault, change to admin_list_wi      
 *    All WF Schema changes are in WFSchema_upgrade_10131_10133.sql
 *
 *    MODIFIED   (MM/DD/YY)
 *    mchinnan   05/16/07 - Backport mchinnan_bug-5995309 from
 *                          st_pcbpel_10.1.3.1
 *    ykumar     03/16/07 - Upgrade script for 10131 to 10133
 *    ykumar     03/16/07 - Created
 *
 */

drop table wi_fault;

/**
 * wi_fault
 *
 * Stores BPEL fault generated by failed attempts to perform a workitem.  
 */
create table wi_fault
(
    cikey           integer,
    node_id         varchar2( 15 ),
    scope_id        varchar2( 15 ),
    count_id        integer,
    domain_ref      smallint,
    fault_name      varchar2( 255 ),
    fault_type      varchar2( 255 ),
    creation_date   timestamp,
    modify_date     timestamp,    
    message         clob
)
storage
(
    freelists 20
);

create index wf_fk1 on wi_fault( cikey, node_id, scope_id, count_id );
create index wf_fk2 on wi_fault( fault_name );

/** 
 * Creating an index for cube_instance table based on the recommendation from bug 5995309
 */
 
create index state_ind on cube_instance( state );
 
/**
 * view admin_list_cx
 *
 * Simple join between cube_instance and ci_indexes tables ... created
 * to allow for consistent administration finder class interface.
 */
create or replace view admin_list_cx
as select ci.cikey, domain_ref as ci_domain_ref, process_id, revision_tag,
          creation_date ci_creation_date, creator ci_creator,
          modify_date ci_modify_date, modifier ci_modifier,
          state ci_state, priority ci_priority, title,
          status, stage, conversation_id, metadata,
          root_id, parent_id,
          index_1, index_2, index_3, index_4, index_5, index_6, ci.test_run_id
   from cube_instance ci, ci_indexes cx
   where ci.cikey = cx.cikey;


/**
 * view admin_list_wi
 *
 * Simple query on the work_item table ... any columns that the
 * work_item table has in common with the cube_instance table are
 * aliased.  The views admin_list_ci, admin_list_wi and admin_list all
 * have the same aliased column names ... this is so the interface to the
 * administration finder class is consistent regardless of the query.
 *
 * Each row contains (incl alias):
 *     + instance id                  (cikey)
 *     + work item node id            (node_id)
 *     + work item scope id           (scope_id)
 *     + work item count id           (count_id)
 *     + work item creation date      (wi_creation_date)
 *     + work item creator            (wi_creator)
 *     + work item modify date        (wi_modify_date)
 *     + work item modifier           (wi_modifier)
 *     + work item state              (wi_state)
 *     + work item priority           (wi_priority)
 *     + work item transition         (transition)
 *     + work item expiration date    (exp_date)
 *     + work item expiration flag    (exp_flag)
 *     + work item label              (label)
 *     + work item custom id          (custom_id)
 *     + work item comments           (comments)
 *     + work item reference id       (reference_id)
 *     + work item execution type     (execution_type)
 *     + instance domain ref          (ci_domain_ref)
 *     + instance process id          (process_id)
 *     + instance revision tag        (revision_tag)
 *     + instance title               (title)
 *     + instance root id             (root_id)
 *     + instance parent id           (parent_id)
 *     + wi_fault fault_name          (fault_name)
 *     + ci_indexes index_1           (index_1)
 *     + ci_indexes index_2           (index_2)
 *     + ci_indexes index_3           (index_3)
 *     + ci_indexes index_4           (index_4)
 *     + ci_indexes index_5           (index_5)
 *     + ci_indexes index_6           (index_6)
 */
create or replace view admin_list_wi
as select wi.cikey, wi.node_id, wi.scope_id, wi.count_id,
          wi.creation_date wi_creation_date, wi.creator wi_creator,
          wi.modify_date wi_modify_date, wi.modifier wi_modifier,
          wi.state wi_state, wi.transition,
          wi.exp_date, exp_flag, wi.priority wi_priority,
          wi.label, wi.custom_id, wi.comments, wi.reference_id,
          wi.execution_type,
          ci.domain_ref as ci_domain_ref,
          ci.process_id process_id, ci.revision_tag revision_tag,
          ci.title title, ci.root_id, ci.parent_id, fault_name,
          index_1, index_2, index_3, index_4, index_5, index_6 
   from cube_instance ci, work_item wi, wi_fault fault, ci_indexes indexes
   where ci.cikey = wi.cikey (+) 
   and fault.cikey (+) = wi.cikey 
   and fault.node_id (+) = wi.node_id 
   and fault.scope_id (+) = wi.scope_id 
   and fault.count_id (+) = wi.count_id 
   and indexes.cikey (+) = ci.cikey ;


@@WFSchema_upgrade_10131_10133.sql

commit;
